//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSiteBangHang.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ThanhVien
    {
        public ThanhVien()
        {
            this.BinhLuans = new HashSet<BinhLuan>();
            this.KhachHangs = new HashSet<KhachHang>();
        }

        public int MaThanhVien { get; set; }
        [DisplayName("Tài khoản")]
        [Required(ErrorMessage = "{0} không được để trống !!!")]

        public string TaiKhoan { get; set; }
        [DisplayName("Mật khẩu")]
        [Required(ErrorMessage = "{0} không được để trống !!!")]
        public string MatKhau { get; set; }
        [DisplayName("Họ tên")]
        [Required(ErrorMessage = "{0} không được để trống !!!")]
        public string HoTen { get; set; }
        [DisplayName("Đại chỉ")]
        [Required(ErrorMessage = "{0} không được để trống !!!")]
        public string DiaChi { get; set; }
        [DisplayName("Email")]
        [RegularExpression(@"\A(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?)\Z",
        ErrorMessage = "Email không hợp lệ")]
        public string Email { get; set; }
        [DisplayName("Số ddienj thoai")]
        [Required(ErrorMessage = "{0} không được để trống !!!")]
        public string SoDienThoai { get; set; }
        [Required(ErrorMessage = "{0} không được để trống !!!")]

        public string CauHoi { get; set; }
        public string CauTraLoi { get; set; }
        public Nullable<int> MaLoaiTV { get; set; }

        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
        public virtual ICollection<KhachHang> KhachHangs { get; set; }
        public virtual LoaiThanhVien LoaiThanhVien { get; set; }
    }
}
